#pragma once

enum ui_object_id {
	ID_NONE,
	ID_TAB_VIEW,
	ID_TAB1,
	ID_TAB2,
	ID_TAB3,
	ID_TAB4,
	ID_TAB_TERMINAL,

	ID_LABEL_LEDS,
	ID_LABEL_GANG,
	ID_LABEL_BLAMP,
	ID_SWITCH_LEDS,
	ID_SWITCH_GANG,
	ID_SWITCH_BLAMP,
	ID_SLIDER_LEDS,
	ID_LABEL_TIME,
	ID_DROPDOWN,
	ID_ROLLER,

	ID_SLIDER_HOEDENPLANK,
	ID_SWITCH_GANGLAMP,
	ID_SWITCH_SCHUUR,
	ID_LABEL_HOEDENPLANK,
	ID_LABEL_GANGLAMP,
	ID_LABEL_SCHUUR,

	ID_TERMINAL_CONTAINER,
	ID_TERMINAL,
	ID_BUTTON_CLEAR,
	ID_BUTTON_CLEAR_LABEL,
	ID_TEXTFIELD_SEARCH,
	ID_KEYBOARD,
};
